apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypod
  labels:
    app: project1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project1
  template:
    metadata:
      labels:
        app: project1
    spec:
      containers:
      - name: tomcat
        image: pravenakumara/guru:v1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  selector:
     app: project1
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
